name:                lab1
version:             0.1.0.0
github:              "as-i-see"
license:             BSD3
author:              "Yevhenii Karlov"
copyright:           "2020 Yevhenii Karlov"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            App category here

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file
description:         Please see the README on GitHub at <https://github.com/Github username here/lab1#readme>

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - array
  - HDBC
  - HDBC-postgresql
  - HUnit
  - tasty
  - tasty-hunit
  - tasty-quickcheck
  - tasty-smallcheck

library:
  source-dirs: src

executables:
  lab1-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - lab1

tests:
  lab1-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - lab1
